### ISSUE TITLE
React.CreateElement and React.PropTypes are deprecated

### ISSUE THREAD

**Issue by romulof** [olahol/react-ab#12]
`React.CreateElement` is deprecated in React 15.5 and will be removed in 16, also PropTypes has migrated to a separate package `prop-types`.

**Comment by panuinth** [comment]
I have the same issue. Seem like CreateElement and PropTypes have dependencies with react-ab.  Anyone have an idea how to fix?

**Comment by olahol** [comment]
Fixed in version `0.5.0` by using `prop-types` and `create-react-class`.
