### ISSUE TITLE
"No display name" on React dev tools

### ISSUE THREAD

**Issue by joaomilho** [olahol/react-ab#4]
I see a "no display name" on React dev tools.

![Dev tools](http://cl.ly/image/2q1y1K292y0q/react-ab-dev-tools.png)

AFAIK it's just a matter of setting it.

**Comment by olahol** [comment]
Thank you for reporting this, just seemed to have missed it.

**Comment by olahol** [comment]
`displayName` now set in version `0.4.4`.
